# Generated by Django 3.2.7 on 2023-10-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scene',
            old_name='characters',
            new_name='cast_id',
        ),
    ]
