# Generated by Django 3.2.7 on 2023-10-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_rename_characters_scene_cast_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
