# Generated by Django 3.2.7 on 2023-10-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_scene_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='cast_id',
        ),
        migrations.AddField(
            model_name='character',
            name='scenes',
            field=models.ManyToManyField(related_name='characters', to='characters.Scene'),
        ),
    ]
