# Generated by Django 3.2.7 on 2023-10-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_auto_20231014_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot', models.CharField(blank=True, max_length=255, null=True)),
                ('take', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
