# Generated by Django 3.2.7 on 2023-10-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_scenedetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SceneDetail',
        ),
    ]
