# Generated by Django 4.2.6 on 2023-10-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_delete_scenedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='scene_number',
            field=models.CharField(max_length=255),
        ),
    ]
