# Generated by Django 4.2.6 on 2023-10-20 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_alter_scene_scene_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='costume_notes',
            field=models.CharField(default=django.utils.timezone.now, max_length=555),
            preserve_default=False,
        ),
    ]
