# Generated by Django 4.2.6 on 2023-10-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_alter_scene_costume_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='costume_notes',
        ),
        migrations.CreateModel(
            name='costume_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scenes', models.ManyToManyField(related_name='costume_notes', to='characters.scene')),
            ],
        ),
    ]
