# Generated by Django 4.2.6 on 2023-10-20 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_remove_scene_costume_notes_costume_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostumeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.scene')),
            ],
        ),
        migrations.DeleteModel(
            name='costume_notes',
        ),
    ]
