# Generated by Django 4.2.6 on 2023-10-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_costumenote_delete_costume_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='cn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
