# Generated by Django 3.2.7 on 2023-10-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_uploadedpdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneDurationRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_number', models.IntegerField()),
                ('duration', models.CharField(max_length=255)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CostumeNote',
        ),
    ]
