# Generated by Django 4.2.6 on 2023-10-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_auto_20231025_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenedurationremark',
            name='scene_number',
            field=models.CharField(max_length=255),
        ),
    ]
