# Generated by Django 4.2.6 on 2023-10-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0017_scenedurationremark_lenscs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenedurationremark',
            name='shotno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
