# Generated by Django 4.2.6 on 2023-10-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0020_scene_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='story',
            field=models.ImageField(blank=True, default='static\\img\x07dd.png', null=True, upload_to='scene_images/'),
        ),
    ]
