# Generated by Django 4.2.6 on 2023-10-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0021_alter_scene_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='avatar',
            field=models.ImageField(blank=True, default='static\\img\x07dd.png', null=True, upload_to='char_images/'),
        ),
    ]
